version: '2'

services:
  tg-captcha-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: marhiiev/tg-captcha-bot:latest
    container_name: tg-captcha-bot
    volumes:
      - ./config.toml:/config.toml
    restart: unless-stopped
    environment:
      - TGTOKEN=your_token
